import os

files = {
    r"c:\Users\pc\Desktop\web_ui\src\components\profile\ProfileViewMode.tsx": [
        ('style={{ paddingBottom: \'2rem\' }}', 'className="profile-container"'),
        ('style={{ fontSize: "1.1rem", margin: 0, color: "var(--text-main)", fontWeight: 600 }}', 'className="card-title"'),
        ('style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "2rem" }}', 'className="dash-card-body grid-3-col"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.85rem", marginBottom: "0.25rem" }}', 'className="label-muted"'),
        ('style={{ fontFamily: "monospace", color: "var(--text-main)", fontSize: "1rem" }}', 'className="value-mono"'),
        ('style={{ marginTop: "1.5rem", marginBottom: "1.5rem" }}', 'className="dash-card card-margin"'),
        ('style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "2rem" }}', 'className="dash-card-body grid-2-col"'),
        ('style={{ gridColumn: "1 / -1" }}', 'className="col-span-all"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.85rem", marginBottom: "0.75rem" }}', 'className="label-muted mb-3"'),
        ('style={{ display: "grid", gap: "0.5rem" }}', 'className="grid-gap-small"'),
        ('style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr 1fr 1fr 1fr", gap: "1rem", padding: "0.75rem 1rem", border: "1px solid var(--surface-border)", borderRadius: "6px", fontFamily: "monospace", fontSize: "0.9rem" }}', 'className="tariff-rule-row"'),
        ('style={{ color: "var(--text-muted)" }}', 'className="text-muted-label"'),
        ('style={{ display: "flex", gap: "3rem" }}', 'className="dash-card-body flex-gap-large"'),
        ('style={{ flex: 1, padding: "1rem", border: "1px solid var(--surface-border)", borderRadius: "8px" }}', 'className="ambr-card"'),
        ('style={{ color: "var(--text-secondary)", fontSize: "0.85rem", textTransform: \'uppercase\', fontWeight: 600 }}', 'className="ambr-label"'),
        ('style={{ color: "var(--text-main)", fontSize: "1.5rem", fontWeight: 600 }}', 'className="ambr-value"'),
        ('style={{ fontSize: "1rem", color: "var(--text-muted)" }}', 'className="ambr-unit"'),
        ('style={{ marginTop: "1.5rem" }}', 'className="dash-card card-margin-top"'),
        ('style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}', 'className="dash-card-header flex-between-center"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}', 'className="flex-center-gap"'),
        ('style={{ background: "transparent", border: "none", cursor: "pointer" }}', 'className="btn-transparent"'),
        ('style={{ paddingTop: "1rem" }}', 'className="pt-1"'),
        ('style={{ fontSize: "1.25rem", marginBottom: "1.5rem", color: "var(--text-main)", fontWeight: 600, display: "flex", alignItems: "center", gap: "0.5rem" }}', 'className="section-title"'),
        ('style={{ padding: "1.5rem 2rem", borderBottom: "1px solid var(--surface-border)", display: "flex", alignItems: "center", gap: "1.5rem" }}', 'className="slice-header"'),
        ('style={{ fontSize: "1.1rem", fontWeight: 600, color: "var(--primary)" }}', 'className="slice-idx"'),
        ('style={{ display: "flex", gap: "1rem", background: "var(--surface-hover)", padding: "0.5rem 1rem", borderRadius: "6px" }}', 'className="slice-tags"'),
        ('style={{ fontWeight: 600 }}', 'className="slice-tag-sst"'),
        ('style={{ color: "var(--text-secondary)" }}', 'className="slice-tag-sd"'),
        ('style={{ padding: "1rem" }}', 'className="p-1"'),
        ('style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.95rem" }}', 'className="table-default"'),
        ('style={{ textAlign: "left", borderBottom: "1px solid var(--surface-border)" }}', 'className="table-header-row"'),
        ('style={{ padding: "1rem" }}', 'className="table-cell-pad"'),
        ('style={{ padding: "1rem", fontWeight: 600, color: "var(--text-main)" }}', 'className="table-cell-main"'),
        ('style={{ padding: "1rem", color: "var(--text-secondary)" }}', 'className="table-cell-sec"'),
        ('style={{ padding: "1rem", color: "var(--text-secondary)", whiteSpace: "nowrap" }}', 'className="table-cell-nowrap"'),
        ('style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}', 'className="flex-col-gap"'),
        ('style={{ background: \'var(--surface-hover)\', padding: \'0.5rem 0.75rem\', borderRadius: \'6px\', fontSize: \'0.85em\', border: \'1px solid var(--surface-border)\' }}', 'className="pcc-rule-card"'),
        ('style={{ fontWeight: 600, color: \'var(--primary)\', marginBottom: \'0.2rem\' }}', 'className="pcc-rule-title"'),
        ('style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.5rem" }}', 'className="pcc-rule-grid"'),
        ('style={{ color: \'var(--text-muted)\' }}', 'className="text-muted-label"'),
        ('style={{ gridColumn: \'span 2\' }}', 'className="col-span-2"'),
        ('style={{ padding: "2rem", textAlign: "center", color: "var(--text-muted)" }}', 'className="empty-state-no-border"'),
        ('style={{ textAlign: "center", color: "var(--text-muted)", padding: "3rem", border: "1px dashed var(--surface-border)", borderRadius: "6px" }}', 'className="empty-state"'),
        ('style={{ borderBottom: "1px solid transparent" }}', 'className="table-row-border"'),
        ('className="dash-card-body" className="dash-card-body grid-3-col"', 'className="dash-card-body grid-3-col"'),
        ('className="dash-card-body" className="dash-card-body grid-2-col"', 'className="dash-card-body grid-2-col"'),
        ('className="dash-card-body" className="dash-card-body flex-gap-large"', 'className="dash-card-body flex-gap-large"'),
        ('className="dash-card" id="psec-ocs-view" className="dash-card card-margin"', 'className="dash-card card-margin" id="psec-ocs-view"'),
        ('className="dash-card" id="psec-access-restrictions" className="dash-card card-margin-top"', 'className="dash-card card-margin-top" id="psec-access-restrictions"'),
        ('className="dash-card-header" className="dash-card-header flex-between-center"', 'className="dash-card-header flex-between-center"'),
        ('className="btn-icon"\\n            onClick', 'className="btn-icon btn-transparent"\\n            onClick'),
        ('className="table-header-cap" className="table-cell-pad"', 'className="table-header-cap table-cell-pad"'),
        ('className="btn-icon"\\n            onClick={() => setIsAccessRestrictionsExpanded((prev: boolean) => !prev)}\\n            title={isAccessRestrictionsExpanded ? t("collapse") : t("expand")}\\n            className="btn-transparent"', 'className="btn-icon btn-transparent"\\n            onClick={() => setIsAccessRestrictionsExpanded((prev: boolean) => !prev)}\\n            title={isAccessRestrictionsExpanded ? t("collapse") : t("expand")}'),
        ('className="btn-icon" onClick={() => setIsAccessRestrictionsExpanded((prev: boolean) => !prev)} title={isAccessRestrictionsExpanded ? t("collapse") : t("expand")} className="btn-transparent"', 'className="btn-icon btn-transparent" onClick={() => setIsAccessRestrictionsExpanded((prev: boolean) => !prev)} title={isAccessRestrictionsExpanded ? t("collapse") : t("expand")}'),
    ],
    r"c:\Users\pc\Desktop\web_ui\src\components\profile\ProfileEditMode.tsx": [
        ('style={{ paddingBottom: \'2rem\' }}', 'className="profile-container"'),
        ('style={{ fontSize: "1.1rem", margin: 0, color: "var(--text-main)", fontWeight: 600 }}', 'className="card-title"'),
        ('style={{ color: "var(--danger)", marginRight: "0.25rem" }}', 'className="danger-asterisk"'),
        ('style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "2rem" }}', 'className="dash-card-body grid-2-col"'),
        ('style={{ gridColumn: "1 / -1" }}', 'className="col-span-all"'),
        ('style={{ fontFamily: "monospace", fontSize: "1.05rem" }}', 'className="font-mono-lg"'),
        ('style={{ display: "flex", gap: "0.75rem" }}', 'className="flex-gap-0-75"'),
        ('style={{ width: "120px", flexShrink: 0 }}', 'className="w-120"'),
        ('style={{ fontFamily: "monospace", fontSize: "1.05rem", flex: 1 }}', 'className="font-mono-lg flex-1"'),
        ('style={{ marginTop: "1rem" }}', 'className="dash-card animate-fade-in edit-card-margin"'),
        ('style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem" }}', 'className="dash-card-body grid-2-col-gap-1-5"'),
        ('style={{ fontFamily: "monospace" }}', 'className="font-mono"'),
        ('style={{ display: "grid", gap: "0.5rem" }}', 'className="grid-gap-small"'),
        ('style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr 1fr 1fr 1fr", gap: "1rem", padding: "0.75rem 1rem", border: "1px solid var(--surface-border)", borderRadius: "6px", background: "var(--surface-hover)", fontFamily: "monospace", fontSize: "0.9rem" }}', 'className="tariff-rule-row-edit"'),
        ('style={{ color: "var(--text-secondary)" }}', 'className="text-muted-label"'),
        ('style={{ color: "var(--text-muted)" }}', 'className="text-muted-label"'),
        ('style={{ marginTop: "1.5rem" }}', 'className="dash-card animate-fade-in card-margin-top"'),
        ('style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}', 'className="dash-card-header flex-between-center"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}', 'className="flex-center-gap"'),
        ('style={{ background: "transparent", border: "none", cursor: "pointer" }}', 'className="btn-transparent"'),
        ('style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "1rem" }}', 'className="access-grid"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.75rem", padding: "0.75rem 1rem", border: "1px solid " + (isChecked ? "var(--primary)" : "var(--surface-border)"), borderRadius: "8px", background: isChecked ? "rgba(59, 130, 246, 0.05)" : "var(--surface)", cursor: "pointer", transition: "all 0.2s" }}', 'className={`access-label ${isChecked ? "access-label-checked" : ""}`}'),
        ('style={{ fontSize: "0.9rem", fontWeight: isChecked ? 600 : 500, color: isChecked ? "var(--primary)" : "var(--text-secondary)" }}', 'className={`access-text ${isChecked ? "access-text-checked" : ""}`}'),
        ('style={{ marginTop: "1.5rem", display: "flex", gap: "1rem", borderTop: "1px solid var(--surface-border)", paddingTop: "1.5rem" }}', 'className="access-actions"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem", padding: "0.4rem 1rem", fontSize: "0.85rem", color: "var(--success)", borderColor: "var(--success)", background: "transparent" }}', 'className="btn-clear-restrictions"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem", padding: "0.4rem 1rem", fontSize: "0.85rem", color: "var(--danger)", borderColor: "var(--danger)", background: "transparent" }}', 'className="btn-suspend-restrictions"'),
        ('style={{ paddingTop: "1rem" }}', 'className="pt-1"'),
        ('style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.5rem" }}', 'className="slice-edit-header"'),
        ('style={{ fontSize: "1.25rem", margin: 0, color: "var(--text-main)", fontWeight: 600, display: "flex", alignItems: "center", gap: "0.5rem" }}', 'className="section-title section-title-margin-0"'),
        ('style={{ padding: \'0.5rem 1rem\', display: "flex", alignItems: "center", gap: "0.4rem", borderRadius: "24px" }}', 'className="btn-add-slice"'),
        ('style={{ textAlign: "center", padding: "4rem", color: "var(--text-muted)", backgroundColor: "var(--surface-hover)", border: "1px dashed var(--surface-border)", borderRadius: "8px" }}', 'className="empty-state-edit"'),
        ('className="dash-card-body" className="dash-card-body grid-2-col"', 'className="dash-card-body grid-2-col"'),
        ('className="dash-card animate-fade-in" id="psec-ocs-edit" className="dash-card animate-fade-in edit-card-margin"', 'className="dash-card animate-fade-in edit-card-margin" id="psec-ocs-edit"'),
        ('className="dash-card-body" className="dash-card-body grid-2-col-gap-1-5"', 'className="dash-card-body grid-2-col-gap-1-5"'),
        ('className="dash-card animate-fade-in" id="psec-access-restrictions" className="dash-card animate-fade-in card-margin-top"', 'className="dash-card animate-fade-in card-margin-top" id="psec-access-restrictions"'),
        ('className="dash-card-header" className="dash-card-header flex-between-center"', 'className="dash-card-header flex-between-center"'),
        ('className="btn-icon"\\n            onClick', 'className="btn-icon btn-transparent"\\n            onClick'),
        ('className="btn btn-outline" className="btn-clear-restrictions"', 'className="btn btn-outline btn-clear-restrictions"'),
        ('className="btn btn-outline" className="btn-suspend-restrictions"', 'className="btn btn-outline btn-suspend-restrictions"'),
        ('className="btn btn-primary" onClick={addSlice} className="btn-add-slice"', 'className="btn btn-primary btn-add-slice" onClick={addSlice}'),
    ],
    r"c:\Users\pc\Desktop\web_ui\src\components\rating\TariffPlanList.tsx": [
        ('style={{ display: "grid", gap: "1.25rem" }}', 'className="grid-gap-1-25"'),
        ('style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 190px), 1fr))", gap: "0.9rem" }}', 'className="stats-grid"'),
        ('style={{ minHeight: 104, padding: "1rem 1.1rem", display: "grid", alignContent: "space-between", gap: "0.8rem" }}', 'className="dash-card stat-card"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.55rem", color: "var(--text-muted)", fontSize: "0.76rem", fontWeight: 850, textTransform: "uppercase" }}', 'className="stat-card-header"'),
        ('style={{ color: "var(--text-main)", fontSize: "1.7rem", lineHeight: 1, fontWeight: 900 }}', 'className="stat-card-value"'),
        ('style={{ overflow: "hidden" }}', 'className="dash-card card-overflow-hidden"'),
        ('style={{ display: "flex", justifyContent: "space-between", gap: "1rem", alignItems: "center" }}', 'className="dash-card-header card-header-flex"'),
        ('style={{ margin: 0, color: "var(--text-main)", fontSize: "1rem", fontWeight: 850 }}', 'className="card-title-lg"'),
        ('style={{ margin: "0.25rem 0 0", color: "var(--text-muted)", fontSize: "0.8rem" }}', 'className="card-desc"'),
        ('style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 260px), 1fr))", gap: "0.75rem" }}', 'className="dash-card-body plans-grid"'),
        ('style={{\\n                        width: "100%",\\n                        textAlign: "left",\\n                        border: `1px solid ${active ? "var(--primary)" : "var(--surface-border)"}`,\\n                        borderRadius: 6,\\n                        background: active ? "color-mix(in srgb, var(--primary) 7%, var(--surface))" : "var(--surface)",\\n                        padding: "0.9rem",\\n                        cursor: "pointer",\\n                        display: "grid",\\n                        gap: "0.65rem",\\n                      }}', 'className={`plan-button ${active ? "plan-button-active" : "plan-button-inactive"}`}\\n                      '),
        ('style={{ display: "flex", justifyContent: "space-between", gap: "0.75rem", alignItems: "flex-start" }}', 'className="plan-header"'),
        ('style={{ minWidth: 0 }}', 'className="plan-title-wrapper"'),
        ('style={{ color: "var(--text-main)", fontWeight: 850, fontSize: "0.9rem", overflowWrap: "anywhere" }}', 'className="plan-title"'),
        ('style={{ color: "var(--text-muted)", fontFamily: "monospace", fontSize: "0.74rem", marginTop: "0.2rem", overflowWrap: "anywhere" }}', 'className="plan-id"'),
        ('style={{ display: "flex", gap: "0.75rem", alignItems: "center", flexWrap: "wrap", color: "var(--text-muted)", fontSize: "0.76rem", fontWeight: 750 }}', 'className="plan-stats"'),
        ('style={{ color: "var(--text-main)" }}', 'className="plan-stat-val"'),
        ('style={{ display: "flex", justifyContent: "space-between", gap: "1rem", alignItems: "flex-start", flexWrap: "wrap" }}', 'className="dash-card-header card-header-flex-wrap"'),
        ('style={{ display: "grid", gap: "0.35rem" }}', 'className="grid-gap-0-35"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.65rem", flexWrap: "wrap" }}', 'className="flex-center-gap-0-65"'),
        ('style={{ margin: 0, color: "var(--text-main)", fontSize: "1.05rem", fontWeight: 850 }}', 'className="card-title-xl"'),
        ('style={{ margin: 0, color: "var(--text-muted)", fontSize: "0.84rem" }}', 'className="card-desc"'),
        ('style={{ display: "flex", gap: "0.55rem", flexWrap: "wrap", justifyContent: "flex-end" }}', 'className="flex-end-gap-0-55"'),
        ('style={{ color: "var(--danger)", borderColor: "var(--danger)" }}', 'className="btn-outline-danger"'),
        ('style={{ display: "grid", gap: "0.85rem" }}', 'className="grid-gap-0-85"'),
        ('style={{ margin: 0, color: "var(--text-main)", fontSize: "0.92rem", fontWeight: 850 }}', 'className="section-subtitle"'),
        ('style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 220px), 1fr))", gap: "1rem", alignItems: "end" }}', 'className="fields-grid"'),
        ('style={{ fontFamily: "monospace", color: "var(--text-secondary)" }}', 'className="input-readonly"'),
        ('style={{ gridColumn: "1 / -1" }}', 'className="col-span-all"'),
        ('style={{ borderTop: "1px solid var(--surface-border)", paddingTop: "1rem", display: "grid", gap: "0.85rem" }}', 'className="usage-overview"'),
        ('style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 150px), 1fr))", gap: "0.8rem" }}', 'className="usage-grid"'),
        ('style={{ border: "1px solid var(--surface-border)", borderRadius: 6, padding: "0.85rem", minWidth: 0 }}', 'className="usage-card"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.72rem", fontWeight: 800, textTransform: "uppercase" }}', 'className="usage-label"'),
        ('style={{ color: "var(--text-main)", fontSize: "1rem", fontWeight: 850, marginTop: "0.35rem", overflowWrap: "anywhere" }}', 'className="usage-val"'),
        ('style={{ color: "var(--danger)", fontSize: "0.82rem", fontWeight: 800, border: "1px solid color-mix(in srgb, var(--danger) 36%, var(--surface-border))", borderRadius: 6, padding: "0.85rem", background: "color-mix(in srgb, var(--danger) 7%, var(--surface))" }}', 'className="disable-warning"'),
        ('style={{ margin: 0, color: "var(--text-main)", fontSize: "1rem", fontWeight: 850, display: "flex", alignItems: "center", gap: "0.55rem" }}', 'className="card-title-lg flex-center-gap-0-55"'),
        ('style={{ margin: "0.35rem 0 0", color: "var(--text-muted)", fontSize: "0.82rem", lineHeight: 1.5 }}', 'className="card-desc-mt desc-line-1-5"'),
        ('style={{ display: "grid", gap: "1rem" }}', 'className="dash-card-body grid-gap-1"'),
        ('style={{ display: "flex", gap: "0.45rem", flexWrap: "wrap" }}', 'className="subs-list"'),
        ('style={{ border: "1px solid var(--surface-border)", borderRadius: 6, padding: "0.28rem 0.5rem", fontFamily: "monospace", fontSize: "0.72rem", color: "var(--text-main)", background: "var(--surface-hover)" }}', 'className="sub-tag"'),
        ('style={{ border: "1px solid var(--surface-border)", borderRadius: 6, padding: "0.28rem 0.5rem", fontSize: "0.72rem", color: "var(--text-muted)", background: "var(--surface-hover)" }}', 'className="sub-tag-more"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.55rem", minHeight: 42, color: "var(--text-secondary)", fontSize: "0.8rem", fontWeight: 700 }}', 'className="migrate-checkbox-label"'),
        ('style={{ minHeight: 42, whiteSpace: "nowrap" }}', 'className="btn-min-height"'),
        ('style={{ margin: "0.35rem 0 0", color: "var(--text-muted)", fontSize: "0.82rem" }}', 'className="card-desc-mt"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.76rem", fontWeight: 750, whiteSpace: "nowrap" }}', 'className="history-count"'),
        ('style={{ border: "1px dashed var(--surface-border)", borderRadius: 6, padding: "1rem", color: "var(--text-muted)", fontSize: "0.83rem" }}', 'className="history-empty"'),
        ('style={{ display: "grid", gap: "0.7rem", maxHeight: 360, overflow: "auto", paddingRight: "0.2rem" }}', 'className="history-list"'),
        ('style={{ borderLeft: `3px solid ${item.level === "warning" ? "var(--danger)" : "var(--primary)"}`, padding: "0.2rem 0 0.2rem 0.75rem", display: "grid", gap: "0.35rem" }}', 'className={`history-item ${item.level === "warning" ? "history-item-warning" : "history-item-primary"}`}'),
        ('style={{ display: "flex", justifyContent: "space-between", gap: "0.75rem", alignItems: "center", flexWrap: "wrap" }}', 'className="history-item-header"'),
        ('style={{ color: item.level === "warning" ? "var(--danger)" : "var(--text-main)", fontWeight: 850, fontSize: "0.84rem" }}', 'className={`history-action ${item.level === "warning" ? "history-action-warning" : "history-action-primary"}`}'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.72rem" }}', 'className="history-time"'),
        ('style={{ display: "flex", gap: "0.8rem", flexWrap: "wrap", color: "var(--text-muted)", fontSize: "0.74rem" }}', 'className="history-details"'),
        ('style={{ fontFamily: "monospace", color: "var(--text-secondary)" }}', 'className="history-target"'),
        ('className="dash-card" className="dash-card stat-card"', 'className="dash-card stat-card"'),
        ('className="dash-card" className="dash-card card-overflow-hidden"', 'className="dash-card card-overflow-hidden"'),
        ('className="dash-card-header" className="dash-card-header card-header-flex"', 'className="dash-card-header card-header-flex"'),
        ('className="dash-card-body" className="dash-card-body plans-grid"', 'className="dash-card-body plans-grid"'),
        ('className="dash-card-header" className="dash-card-header card-header-flex-wrap"', 'className="dash-card-header card-header-flex-wrap"'),
        ('className="dash-card-body" className="dash-card-body grid-gap-1"', 'className="dash-card-body grid-gap-1"'),
        ('className="btn btn-outline" onClick={handleDeletePlan} disabled={savingKey !== null || selectedPlanSubscriberTotal > 0} className="btn-outline-danger"', 'className="btn btn-outline btn-outline-danger" onClick={handleDeletePlan} disabled={savingKey !== null || selectedPlanSubscriberTotal > 0}'),
        ('className="btn btn-primary"\\n                      onClick={handleMigratePlanSubscribers}\\n                      disabled={savingKey !== null || !migrationTargetPlanId || selectedPlanSubscriberTotal === 0}\\n                      className="btn-min-height"', 'className="btn btn-primary btn-min-height"\\n                      onClick={handleMigratePlanSubscribers}\\n                      disabled={savingKey !== null || !migrationTargetPlanId || selectedPlanSubscriberTotal === 0}'),
    ],
    r"c:\Users\pc\Desktop\web_ui\src\components\rating\PccRuleList.tsx": [
        ('style={{ overflow: "hidden" }}', 'className="dash-card card-overflow-hidden"'),
        ('style={{ display: "grid", gridTemplateColumns: "minmax(240px, 1fr) auto", gap: "1rem", alignItems: "center" }}', 'className="dash-card-header card-header-grid"'),
        ('style={{ display: "grid", gap: "0.3rem" }}', 'className="grid-gap-0-35"'),
        ('style={{ margin: 0, color: "var(--text-main)", fontSize: "1rem", fontWeight: 850 }}', 'className="card-title-lg"'),
        ('style={{ margin: 0, color: "var(--text-muted)", fontSize: "0.82rem" }}', 'className="card-desc"'),
        ('style={{ minHeight: 38, whiteSpace: "nowrap" }}', 'className="btn-new-rate"'),
        ('style={{ gridColumn: "1 / -1", display: "grid", gridTemplateColumns: "minmax(220px, 0.85fr) minmax(300px, 1.25fr) minmax(260px, 0.9fr)", alignItems: "end", gap: "0.85rem", borderTop: "1px solid var(--surface-border)", paddingTop: "0.85rem" }}', 'className="filters-grid"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem", flexWrap: "wrap" }}', 'className="filters-flex"'),
        ('style={{ height: 34, padding: "0 0.75rem", display: "inline-flex", alignItems: "center", gap: "0.4rem", borderRadius: 6 }}', 'className="filter-btn"'),
        ('style={{ opacity: 0.75 }}', 'className="filter-count"'),
        ('style={{ position: "relative", minWidth: 0 }}', 'className="search-wrapper"'),
        ('style={{ position: "absolute", left: 12, top: "50%", transform: "translateY(-50%)", color: "var(--text-muted)" }}', 'className="search-icon"'),
        ('style={{ paddingLeft: 36, height: 38 }}', 'className="search-input"'),
        ('style={{ overflowX: "auto" }}', 'className="table-container"'),
        ('style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.95rem", minWidth: "980px" }}', 'className="rule-table"'),
        ('style={{ background: "var(--surface-hover)", borderBottom: "2px solid var(--surface-border)" }}', 'className="rule-table-thead"'),
        ('style={{ padding: "1rem 1.5rem", textAlign: "left", width: "190px" }}', 'className="rule-th rule-th-id"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}', 'className="flex-center-gap"'),
        ('style={{ padding: "1rem 1.5rem", textAlign: "left" }}', 'className="rule-th"'),
        ('style={{ padding: "1rem 1.5rem", textAlign: "right", width: "120px" }}', 'className="rule-th rule-th-actions"'),
        ('style={{ background: "rgba(59, 130, 246, 0.08)", borderBottom: "1px solid var(--surface-border)" }}', 'className="rule-tr-adding"'),
        ('style={{ borderBottom: "1px solid var(--surface-border)" }}', 'className="rule-tr"'),
        ('style={{ padding: "1.15rem 1.5rem" }}', 'className="rule-td"'),
        ('style={{ fontFamily: "monospace", fontWeight: 800, color: "var(--primary)", fontSize: "1.05rem" }}', 'className="rule-id"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.76rem", marginTop: "0.25rem", overflowWrap: "anywhere" }}', 'className="rule-subid"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.55rem", color: meta.color, fontWeight: 800 }}', 'className="rule-scenario" style={{ color: meta.color }}'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.8rem", marginTop: "0.3rem" }}', 'className="rule-scenario-desc"'),
        ('style={{ fontFamily: "monospace", color: "var(--text-main)" }}', 'className="rule-font-mono-main"'),
        ('style={{ margin: "0 0.45rem" }}', 'className="rule-dot"'),
        ('style={{ fontFamily: "monospace", fontWeight: 800, color: "var(--text-main)" }}', 'className="rule-rate"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.8rem", marginTop: "0.3rem" }}', 'className="rule-rate-type"'),
        ('style={{ display: "flex", alignItems: "center", gap: "0.5rem", fontWeight: 800 }}', 'className="rule-grant"'),
        ('style={{ color: "var(--text-muted)", fontSize: "0.8rem", marginTop: "0.3rem" }}', 'className="rule-grant-desc"'),
        ('style={{ background: "rgba(16, 185, 129, 0.12)", color: "var(--success)", padding: "4px 10px", borderRadius: "999px", fontSize: "0.78rem", fontWeight: 800 }}', 'className="rule-status"'),
        ('style={{ padding: "1.15rem 1.5rem", textAlign: "right" }}', 'className="rule-actions"'),
        ('style={{ display: "flex", gap: "0.5rem", justifyContent: "flex-end" }}', 'className="rule-actions-flex"'),
        ('className="dash-card" className="dash-card card-overflow-hidden"', 'className="dash-card card-overflow-hidden"'),
        ('className="dash-card-header" className="dash-card-header card-header-grid"', 'className="dash-card-header card-header-grid"'),
        ('className={active ? "btn btn-primary" : "btn btn-outline"}\\n                    onClick={() => setFilter(key)}\\n                    className="filter-btn"', 'className={`${active ? "btn btn-primary" : "btn btn-outline"} filter-btn`}\\n                    onClick={() => setFilter(key)}'),
        ('className="btn btn-primary" onClick={() => setIsAdding(true)} disabled={savingKey !== null || isAdding} className="btn-new-rate"', 'className="btn btn-primary btn-new-rate" onClick={() => setIsAdding(true)} disabled={savingKey !== null || isAdding}'),
        ('className="form-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("rating_search_ph")} className="search-input"', 'className="form-input search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("rating_search_ph")}'),
        ('className="table-header-cap" className="rule-th rule-th-id"', 'className="table-header-cap rule-th rule-th-id"'),
        ('className="table-header-cap" className="rule-th"', 'className="table-header-cap rule-th"'),
        ('className="table-header-cap" className="rule-th rule-th-actions"', 'className="table-header-cap rule-th rule-th-actions"'),
    ]
}

def inject_import(content, filepath):
    if 'import "./profile.css";' in content or 'import "./rating.css";' in content:
        return content
    css_import = 'import "./profile.css";\\n' if 'profile' in filepath else 'import "./rating.css";\\n'
    # insert after the first import or use "use client"
    if content.startswith('"use client";\\n'):
        return content.replace('"use client";\\n', '"use client";\\n' + css_import, 1)
    elif content.startswith("import"):
        # find end of first line
        parts = content.split("\\n", 1)
        return parts[0] + "\\n" + css_import + parts[1]
    return css_import + content

for filepath, replacements in files.items():
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for old, new in replacements:
            content = content.replace(old, new)
            
        content = inject_import(content, filepath)
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated {filepath}")
    else:
        print(f"File not found {filepath}")
