package auth

import (
	"encoding/json"
	"os"
	"testing"
)

// nodeFixture is the structure of backend/testdata/auth/node-jose-token.json.
type nodeFixture struct {
	Description string             `json:"description"`
	Library     string             `json:"library"`
	Algorithm   string             `json:"algorithm"`
	TestSecret  string             `json:"testSecret"`
	Fixtures    map[string]fixture `json:"fixtures"`
}

type fixture struct {
	Description string        `json:"description"`
	Token       string        `json:"token"`
	Claims      fixtureClaims `json:"claims"`
}

type fixtureClaims struct {
	Username string `json:"username"`
	Role     string `json:"role"`
	SV       int64  `json:"sv"`
}

func loadNodeFixture(t *testing.T) nodeFixture {
	t.Helper()
	// Walk up from internal/auth/ to backend/testdata/auth/
	path := "../../testdata/auth/node-jose-token.json"
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("load fixture: %v (run: node scripts/migration/generate-auth-fixture.mjs)", err)
	}
	var f nodeFixture
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	return f
}

// TestNodeJoseInterop_ValidToken verifies that a JWT generated by Node jose
// can be verified by the Go HS256 verifier with correct claims.
func TestNodeJoseInterop_ValidToken(t *testing.T) {
	f := loadNodeFixture(t)
	secret := []byte(f.TestSecret)

	valid, ok := f.Fixtures["valid"]
	if !ok {
		t.Fatal("fixture missing 'valid' entry")
	}

	claims, err := VerifyJWT(valid.Token, secret)
	if err != nil {
		t.Fatalf("VerifyJWT(valid) error: %v", err)
	}

	if claims.Username != valid.Claims.Username {
		t.Errorf("Username = %q, want %q", claims.Username, valid.Claims.Username)
	}
	if claims.Role != valid.Claims.Role {
		t.Errorf("Role = %q, want %q", claims.Role, valid.Claims.Role)
	}
	if claims.SV != valid.Claims.SV {
		t.Errorf("SV = %d, want %d", claims.SV, valid.Claims.SV)
	}

	t.Logf("Node jose → Go verifier: PASS (username=%s, role=%s, sv=%d)",
		claims.Username, claims.Role, claims.SV)
}

// TestNodeJoseInterop_ExpiredToken verifies that Go rejects an expired
// token generated by Node jose.
func TestNodeJoseInterop_ExpiredToken(t *testing.T) {
	f := loadNodeFixture(t)
	secret := []byte(f.TestSecret)

	expired, ok := f.Fixtures["expired"]
	if !ok {
		t.Fatal("fixture missing 'expired' entry")
	}

	_, err := VerifyJWT(expired.Token, secret)
	if err == nil {
		t.Fatal("expected error for expired Node jose token")
	}
	if !contains(err.Error(), "expired") {
		t.Errorf("error = %q, want contains 'expired'", err.Error())
	}
}

// TestNodeJoseInterop_AlgNone verifies that Go rejects an alg=none
// token crafted to look like a Node jose output.
func TestNodeJoseInterop_AlgNone(t *testing.T) {
	f := loadNodeFixture(t)
	secret := []byte(f.TestSecret)

	algNone, ok := f.Fixtures["algNone"]
	if !ok {
		t.Fatal("fixture missing 'algNone' entry")
	}

	_, err := VerifyJWT(algNone.Token, secret)
	if err == nil {
		t.Fatal("expected error for alg=none token")
	}
	if !contains(err.Error(), "algorithm") {
		t.Errorf("error = %q, want contains 'algorithm'", err.Error())
	}
}
